%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Mono"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Mono"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
# ez is jo ha be van allitva
Camera1.fx: 664.2
Camera1.fy: 664.2
Camera1.cx: 481.7785
Camera1.cy: 366.039 

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

# Original settins
# Camera.width: 752
# Camera.height: 480

# Camera.newWidth: 600
# Camera.newHeight: 350
#Camera height-width és a "new" csak annyiban érdekes, hogy a new a vizualizációnál van használva.
 
#Stereo.ThDepth: mélység korlát, csak a stereoTrackingben használt
#Stereo.B: a sztereo camera baseline értéke. RGBD esetben nincs értelme, nem használja a config csak a StereoTracking-nél,
#amúgy a bal és jobb sztereo kamera közti távolság
# EZT PONTOSAN BE KELL ALLITANI!! 
Camera.width: 960
Camera.height: 720 # CHANGE BACK TO 1200

Camera.newWidth: 640
Camera.newHeight: 480

# Camera frames per second 
Camera.fps: 50 # CHANGE BACK TO 15

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

Camera.ThDepth: 11.0

Stereo.ThDepth: 11.0  # Required parameter for RGB-D
Stereo.b: 0.075      # Baseline (in meters), required for RGB-D

RGBD.DepthMapFactor: 1000.0
RGBD.MinDepth: 0.1   # Minimum depth in meters
RGBD.MaxDepth: 11.0  # Maximum depth in meters

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000 ## CHANGE BACK TO 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2 ## CHANGE BACK TO 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8 ## CHANGE BACK TO 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

## custom params...
#ORBextractor.minFrames: 10
#ORBextractor.RansacThreshold: 3.0


#--------------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0 # 500

