%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Mono"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Mono"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
#Camera1.fx: 971.2424832242577
#Camera1.fy: 977.2791610306153
#Camera1.cx: 960.0
#Camera1.cy: 540.0
#
#Camera1.k1: 0.0
#Camera1.k2: 0.0
#Camera1.p1: 0.0
#Camera1.p2: 0.0

Camera1.fx: 573.69378662 # 1548.973266 # 1920x1080
Camera1.fy: 573.92248535 # 1549.590698  # 1920x1080
Camera1.cx: 312.81414795 # 940.598205  # 1920x1080
Camera1.cy: 205.95597839 # 556.081176  # 1920x1080

Camera1.k1: 4.4872660636901855
Camera1.k2: -62.17211151123047
Camera1.p1: 0.00009906007471727207
Camera1.p2: -0.0016796315321698785
Camera1.k3: 197.63162231445312
Camera1.k4: 4.298056602478027
Camera1.k5: -60.94719696044922
Camera1.k6: 194.32264709472656

#Camera1.k1: 5.298761367797852
#Camera1.k2: -60.44940185546875
#Camera1.p1: 0.0006572440033778548
#Camera1.p2: -0.0004981404053978622
#Camera1.k3: 238.7996063232422
#Camera1.k4: 5.10204553604126
#Camera1.k5: -59.198429107666016
#Camera1.k6: 234.19580078125

# Original settins
# Camera.width: 752
# Camera.height: 480

# Camera.newWidth: 600
# Camera.newHeight: 350

Camera.width: 640
Camera.height: 400 # CHANGE BACK TO 1200

Camera.newWidth: 640
Camera.newHeight: 400

# Camera frames per second 
Camera.fps: 15 # CHANGE BACK TO 15

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

Camera.ThDepth: 10.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000 ## CHANGE BACK TO 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2 ## CHANGE BACK TO 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8 ## CHANGE BACK TO 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

## custom params...
#ORBextractor.minFrames: 10
#ORBextractor.RansacThreshold: 3.0


#--------------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0 # 500

#--- new params

RGBD.DepthMapFactor: 1000.0
Stereo.ThDepth: 3.0
Stereo.b: 0.0075